name: MinecraftPaintball
version: '${project.version}'
main: me.gorgeousone.paintball.PaintballPlugin
api-version: 1.13
depend: [WorldEdit]
commands:
    paintball:
        aliases: [pb]
permissions:
    paintball.configure:
        default: op
    paintball.moderator:
        default: op
    paintball.debug:
        default: op
